### ISSUE TITLE
Status always 0

### ISSUE THREAD

**Issue by mpena2099** [KumarRobotics/ublox#134]
On u-blox IDE the status looks OK (fix mode):

![gnss](https://user-images.githubusercontent.com/1200886/120859831-2a75ef80-c55b-11eb-97c1-6b59a66158e4.png)

0 invalid
1 2D/3D
2 DGNSS
4 Fixed RTK
5 Float RTK
6 Dead Reckoning

So, on ROS topic, status have to be 1. Right?

$ rostopic echo /ublox/fix

```
header: 
  seq: 136
  stamp: 
    secs: 1622838693
    nsecs: 750246994
  frame_id: "gps"
status: 
  status: 0
  service: 1
latitude: -XX.2070401
longitude: -XX.7940134
altitude: 528.4
position_covariance: [1.283689, 0.0, 0.0, 0.0, 1.283689, 0.0, 0.0, 0.0, 6.091024]
position_covariance_type: 2
---

```

And... it is always 0. My YAML:
```

device: /dev/ttyACM0
frame_id: gps
uart1:
  baudrate: 38400
config_on_startup: false

```

Any idea what could be wrong? Thanks!
