### ISSUE TITLE
Unable to get sensor_msgs/Imu data from simpleRTK2B SBC Board with ZED F9P ublox

### ISSUE THREAD

**Issue by adityajadhav99** [KumarRobotics/ublox#172]
I am using an Ardusimple [simpleRTK2B](https://www.ardusimple.com/product/simplertk2b-sbc-development-kit/) with three ZED F9P GPS units. My aim is to get the GPS and Imu data from the board. Currently, I am just getting the GPS data (10 Hz) and a topic called /ublox/navheading with all zeros in the message data fields.

These are files that I am using:
### zed_f9p.yaml:
```
debug: 1

device: /dev/ttyACM0
frame_id: gps
# raw_data: true
uart1:
  baudrate: 57600
config_on_startup: false

rate: 10
nav_rate: 10

gnss:
  glonass: true            
  beidou: true             
  qzss: true               

publish:
  all: true
  esf:
    meas: true
```
### ublox_device.launch:
```
<?xml version="1.0" encoding="UTF-8"?>

<launch>
  <arg name="param_file_name"     default="zed_f9p"/>
  <arg name="param_file_dir"      default="$(find ublox_gps)/config" />

  <arg name="node_name"           doc="name of this node"
                                  default="ublox" />
  <arg name="output"              default="screen" />
  <arg name="respawn"             default="true" />
  <arg name="respawn_delay"       default="30" />
  <arg name="clear_params"        default="true" />

  <node pkg="ublox_gps" type="ublox_gps" name="$(arg node_name)"
        output="$(arg output)"
        clear_params="$(arg clear_params)"
        respawn="$(arg respawn)"
        respawn_delay="$(arg respawn_delay)">
    <rosparam command="load"
              file="$(arg param_file_dir)/$(arg param_file_name).yaml" />

    <remap from="/ublox/fix" to="/ardusimple/gnss" />
    <remap from="/ublox/fix_velocity" to="/ardusimple/odometry" />
  </node>
</launch> 
```
when I launch the file ```ublox_device.launch```, the following topics appear:
```
/ardusimple/gnss
/ardusimple/odometry
/diagnostics
/rosout
/rosout_agg
/rtcm
/ublox/hp_fix
/ublox/monhw
/ublox/navclock
/ublox/navheading
/ublox/navhpposecef
/ublox/navhpposllh
/ublox/navposecef
/ublox/navpvt
/ublox/navrelposned
/ublox/navsat
/ublox/navstatus
```
When I echo ```/ublox/navheading```, following messages appear:
```
header: 
  seq: 869
  stamp: 
    secs: 1658308948
    nsecs: 965187326
  frame_id: "gps"
orientation: 
  x: 0.0
  y: 0.0
  z: 0.7071067811865475
  w: 0.7071067811865476
orientation_covariance: [1000.0, 0.0, 0.0, 0.0, 1000.0, 0.0, 0.0, 0.0, 1000.0]
angular_velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
angular_velocity_covariance: [-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: 0.0
  y: 0.0
  z: 0.0
linear_acceleration_covariance: [-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
```
**This means the IMU data is not being outputted. If anyone knows how to solve the problem please do let me know.**
