### ISSUE TITLE
uart1:baudrate cannot be configured on f9p

### ISSUE THREAD

**Issue by Timple** [KumarRobotics/ublox#77]
Also holds for:
```yaml
uart1:
  baudrate:
  in:
  out:
uart2:
  baudrate:
  in:
  out:
gnss:
  gps: 
  glonass: 
  beidou: 
```

USB baudrate still works though.

Seems like the interface description has changed more than expected / implemented in #64 
The list above is what we encountered and is not a full list.

Basic operation works though including the imu heading message.
